# -*- coding: utf-8 -*-
"""CSE110 Lab Assignment 4 (List).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zJ-8m1ZWOfJIgKsmnL-UrS_7F_c8biu7
"""

a="7 12 4 55 96 2 11 61 33 42"
final_list=[]
new_list=''
for i in range(len(a)):
  if a[i]!=' ':
    new_list+=a[i] #nwLst="78"
  else:
    final_list.append(int(new_list)) #fnl_lst=['12','45']
    new_list=""
final_list.append(int(new_list)) #fnl_lst=['12','45','78']
print(final_list)

s="12 45 78"
#print(s[3:5])
for i in range(len(s)):
  if s[i]==" ":
    print(s[:i])

"""# CSE110 Lab Assignment 4

This Assignment is to help you develop your concept of Lists in Python.

##Write your name, student ID and CSE110 theory section number below:
"""

#STUDENT NAME:
#STUDENT ID:
#CSE110 THEORY SECTION:

"""## Write the code in Python to do the following tasks:

**<font color='red'>[MUST MAINTAIN VARIABLE NAMING CONVENTIONS FOR ALL THE TASKS]</font>**

### Task 1
Write a Python program that reads 10 numbers from the user into a list. After reading each number, print all the numbers that have been entered so far in the list. 

**Example:**\
After the user enters 3, prints “Numbers in the list: [3]”\
After the user enters 5, prints “Numbers in the list: [3, 5]”\
After the user enters 34, prints “Numbers in the list: [3, 5, 34]”\
.... and so on
"""

#to do
lst=[]
for i in range(5):
  n=int(input("Enter a number: "))
  lst.append(n)
  print(lst)

"""### Task 2

Write a Python program that takes a list as an input from the user.Then creates a new list excluding the first and last two elements of the given list and prints the new list. If there are not enough elements in the list to do the task, the print "Not possible".

**Note:** You may use list slicing.

===================================================================

**Sample Input 1:**<br/>
[10, 20, 24, 25, 26, 35, 70]<br/>
**Sample Output 1:**<br/>
[24, 25, 26]<br/>

===================================================================

**Sample Input 2:**<br/>
[10, 20, 24, 25, 26]<br/>
**Sample Output 2:**<br/>
[24]<br/>

===================================================================

**Sample Input 3:**<br/>
[10, 20, 24, 25]<br/>
**Sample Output 3:**<br/>
[]<br/>

===================================================================

**Sample Input 4:**<br/>
[10, 20, 24]<br/>
**Sample Output 4:**<br/>
Not possible<br/>

===================================================================
"""

#to do
lst=[10, 20, 24, 25,26]
nw_lst=[]
if len(lst)>3:
  nw_lst[:]=lst[2:len(lst)-2]
  print(nw_lst)
else:
  print("Not Possible")

"""### Task 3

Write a python program that reads 5 numbers from the user into a list, and then prints them in the reverse order.

*Hint: You may create a list to store the input numbers and then use loop to print them in reverse order*

===================================================================

**Sample Input:**\
5\
-5\
100\
1\
0

**Sample Output:**\
Input data: [5, -5, 100, 1, 0]\
Printing values from the list in reverse order:\
0\
1\
100\
-5\
5

===================================================================
"""

#to do
lst=[]
for i in range(5):
  n=int(input("Enter numbers: "))
  lst.append(n)
print(lst[::-1])

"""### Task 4

Write a Python program that turns every item of a list into its square. [Your program should work for any lists; make changes to the lists below and check whether your program works correctly]

===================================================================

**Given list 1:**\
[1, 2, 3, 4, 5, 6, 7]

**Sample Output 1:**\
[1, 4, 9, 16, 25, 36, 49]

===================================================================

**Given list 2:**\
[3, 5, 1, 6]

**Sample Output 2:**\
[9, 25, 1, 36]


===================================================================






"""

#to do

"""### Task 5


Write a Python program that removes all Empty strings from a **given list** and print the modified list. [Your program should work for any given list; make changes to the lists below and check whether your program works correctly]

=========================================================================

**Given List:**

["hey", "there", "", "what's", "", "up", "", "?"]

**Sample Output:**

Original List:
['hey', 'there', '', "what's", '', 'up', '', '?']

Modified List:
['hey', 'there', "what's", 'up', '?']

==========================================================================



"""

#to do
lst=["hey", "there", "", "what's", "", "up", "", "?"]
for i in lst:
  if i=="":
    lst.remove(i)
print(f"modified: {lst}")



"""### Task 6

Write a Python program that reads 5 numbers into a list and prints the **largest number** and its location or index position on the list. <font color='red'>[You are not allowed to use the max(), sort(), sorted() function here]</font>

**Hint:** You may assume the first input to be the largest value initially and the largest value’s location to be 0.

**Note:** You may need to be careful while printing the output. Depending on your code, you might need data conversion.

===================================================================

**Sample Input:**\
 7, 13, 2, 10, 6

**Sample Output:**\
My list: [7, 13, 2, 10, 6]\
Largest number in the list is 13 which was found at index 1.

===================================================================
"""

#to do

"""## Task 7

Suppose you have been given two lists. Write a Python program that replaces the last element of the first list with the second list. [Your program should work for any two given lists; make changes to the lists below and check whether your program works correctly]


===================================================================

**Sample given lists 1:**\
List_one : [1, 4, 7, 5]\
List_two : [6, 1, 3, 9]

**Sample Output 1:**\
[1, 4, 7, 6, 1, 3, 9]

===================================================================

**Sample given lists 2:**\
List_one : [1, 3, 5, 7, 9, 10]\
List_two : [2, 4, 6, 8]

**Sample Output 2:**\
[1, 3, 5, 7, 9, 2, 4, 6, 8]

===================================================================




"""

#to do
l1=[1, 4, 7, 5]
l2=[6, 1, 3, 9]
m=len(l1)
nw_lst=l1[:m-1]+l2
print(nw_lst)

"""### Task 8
Assume, you have been given two lists. [Your program should work for any two given lists; change the following lists and check whether your program works correctly for the code you have written]

list_one = [1, 2, 3, 4, 5, 6, 7, 8, 9]\
list_two = [10, 11, 12, -13, -14, -15, -16]

Write a Python program that creates a new list with all the **even elements** of both of the given lists and prints the new list.

**Hint:** You may create a third list to store the even elements of the given lists.

===================================================================

**Output for the above lists:** [2, 4, 6, 8, 10, 12, -14, -16]

===================================================================
"""

#to do
list_one = [1, 2, 3, 4, 5, 6, 7, 8, 9]
list_two = [10, 11, 12, -13, -14, -15, -16]
l_three=[]
l1=len(list_one)
l2=len(list_two)

for i in range(l1):
  if list_one[i]%2==0:
    l_three.append(list_one[i])
for i in range(l2):
  if list_two[i]%2==0:
    l_three.append(list_two[i])
print(l_three)

"""### Task 9

Write a Python program that reads a string as an input from the user where multiple numbers are separated by spaces. Then, make a list of numbers from the input string without using the split() function and print the list. Finally, remove all the occurences of **even numbers** from the same input list and print the modified list.


=========================================================================

**Sample Input:**

7 12 4 55 96 2 11 61 33 42

**Sample Output:**

Original list: [7, 12, 4, 55, 96, 2, 11, 61, 33, 42]\
Modified list: [7, 55, 11, 61, 33]

=========================================================================




"""

#to do
s='7 12 4 55 96 2 11 61 33 42'

lst=[]
mod_list=[]
j=0
for i in range(len(s)):
  if s[i]==" ":
    lst.append(int(s[j:i]))
    j=i+1
for i in range(len(lst)):
  if lst[i]%2!=0:
    mod_list.append(lst[i])
print(f"Original : {lst}")
print(f"Modified : {mod_list}")

"""### Task 10
Write a Python program that reads a string as an input from the user where multiple numbers are separated by commas. Then, make a list of numbers from the input string and print the list. Finally, remove multiple occurences of any numbers from the input list and print the modified list **without duplicate values**.

*Hint: You may create a third list to store the results but try doing it in the same input list. You can use membership operators (in, not in) to make sure no duplicates are added.*

===================================================================

**Sample Input 1:**<br/>
0, 0, 1, 2, 3, 4, 4, 5, 6, 6, 6, 7, 8, 9, 4, 4<br/>


**Sample Output 1:**<br/>
Input list: [0, 0, 1, 2, 3, 4, 4, 5, 6, 6, 6, 7, 8, 9, 4, 4]\
Modified list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

===================================================================

**Sample Input 2:**<br/>
7, 7, 7, 1, 0, 3, 3, 55, 9<br/>


**Sample Output 2:**<br/>
Input list: [7, 7, 7, 1, 0, 3, 3, 55, 9]\
Modified list: [7, 1, 0, 3, 55, 9]

===================================================================
"""

#to do
lst=[0, 0, 1, 2, 3, 4, 4, 5, 6, 6, 6, 7, 8, 9, 4, 4]
nw_lst=[]
for i in lst:
  if i not in nw_lst:
    nw_lst.append(i)
print(nw_lst)

"""### Task 11
Assume, you have been given two lists: List_one and List_two. [Your program should work for any two given lists; change the following lists and check whether your program works correctly for the code you have written]

Write a Python program that prints "True", if the given two lists have at least one common member. Otherwise, prints "False". 

Note: Please use concepts of flag and break to solve this task.

===================================================================

**Given lists 1:**\
List_one : [1, 4, 3, 2, 6]\
List_two : [5, 6, 9, 8, 7]

**Sample Output 1:**\
True

===================================================================

**Given lists 2:**\
List_one : [1, 4, 3, 2, 5]\
List_two : [8, 7, 6, 9]

**Sample Output 2:**\
False

===================================================================

"""

#to do
l1=[1, 4, 3, 2, 5]
l2=[8, 7,6,9]

for i in l2:
  if i in l1:
    print("True")
    break
else:
  print("False")

#task12
myList = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
index1 = 0
index2 = 0
index1 = 1
while(index1<10):
  myList[index1] = index1+4
  index2 = 1
  while(index2<index1):
      myList[index1] = myList[index1] + myList[index2]-index1
      index2 = index2+1
  print(myList[index1])
  index1 = index1+1

#Task13
myList = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
index1 = 0
index2 = 0
index1 = 1
while (index1 < 10):
  myList[index1] = index1 + 4
  index2 = 1
  while (index2 < index1):
    myList[index1] = myList[index1-1] - myList[index2-1] - index1
    index2 = index2 + 1
  print(myList[index1])
  index1 = index1 + 1

#task14

myList = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
b = []
index1 = 0
index2 = 0
index1 = 1
b = myList
while(index1<10):
  myList[index1] = index1+2
  index2 = 1
  while(index2<index1):
    myList[index1] = b[index1]+myList[index2]-index1
    index2 = index2+1
  print(myList[index1])
  index1 = index1+1

#Task15

myList = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
b = []
index1 = 0
index2 = 0
index1 = 1
b = myList
while (index1 < 10):
  myList[index1] = index1 + 1
  index2 = 1
  while (index2 < index1):
    myList[index1] = b[index2-1] + myList[index2] - index1
    index2 = index2 + 1
  print(myList[index1])
  index1 = index1 + 1

"""## Optional Tasks (12-17) [Ungraded]

### Task 12


Write a Python program that reads 5 numbers into a list and prints the **second largest number** and its location or index position on the list. <font color='red'>[You are not allowed to use the max(), sort(), sorted() function here]</font>

===================================================================

**Sample Input:**\
 7, 13, 2, 10, 6

**Sample Output:**\
My list: [7, 13, 2, 10, 6]\
Second largest number in the list is 10 which was found at index 3.

===================================================================
"""

#to do

"""### Task 13

Write a Python program that reads 5 numbers into a list and prints the smallest and largest number and their locations in the list. <font color='red'>[You are not allowed to use the max(), min(), sort(), sorted() functions here]</font>

**Hint:** You may assume the first input to be the largest value initially and the largest value’s location to be 0. Similarly, you can assume the first input to be the smallest value initially and the smallest value’s location to be 0. 

**Note:** You may need to be careful while printing the output. Depending on your code, you might need data conversion.

===================================================================

**Sample Input:**\
7, 13, -5, 10, 6

**Sample Output:**\
My list: [7, 13, -5, 10, 6]\
Smallest number in the list is -5 which was found at index 2\
Largest number in the list is 13 which was found at index 1

===================================================================
"""

#to do

"""### Task 14
Write a Python program that takes two lists as an input from the user. Then print a new list with the **common elements** of both the input lists. 

*Hint: You may need to create a third list to store the results. You can use membership operators (in, not in) to make sure similar elements are added.*

===================================================================

**Sample Input 1:**<br/>
A, B, C, D


C, E, F, B


**Sample Output 1:**<br/>
['C', 'B']

===================================================================

**Sample Input 2:**<br/>
1, 3, A, H, P


A, G, 1, P, O


**Sample Output 2:**<br/>
['1', 'A', 'P']

===================================================================

"""

# to do

"""### Task 15

Assume, you have been given two lists. [Your program should work for any two given lists; make changes to the lists below and check whether your program works correctly]

list_one = [1, 2 , 2, 4, 5, 5, 7, 99, 200, 303, 70]\
list_two = [1, 1, 2, 3, 3, 3, 4, 5, 200, 500, -5]

Write a Python program that creates a new list with all the **unique elements** of both the given lists. 
<font color='red'> **You need to make sure that there are no duplicates in the resulting list.**</font> Finally, print the updated list.

**Hint:** You may create a third list to store the results. You can use membership operators (in, not in) to make sure no duplicates are added.

===================================================================

**Output for the above two lists**: 
[1, 2, 4, 5, 7, 99, 200, 303, 70, 3, 500, -5]

===================================================================
"""

# to do

"""### Task 16

Write a python program to take a list as a input from the user and print it back to the user. 

**<font color='red'>[Must use string split() and strip() functions]</font>**

================================================================

**Sample Input 1:**\
'1, &nbsp; &nbsp;&nbsp; &nbsp; 2  ,&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;3, 50, 4'

**Sample Output 1:**\
Original data: '1, &nbsp; &nbsp;&nbsp; &nbsp; 2  ,&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;3, 50, 4'\
After removing square brackets: 1, &nbsp; &nbsp;&nbsp; &nbsp; 2  ,&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;3, 50, 4\
Numbers in string format with extra white spaces: ['1', '&nbsp; &nbsp;&nbsp; &nbsp; 2'  ,'&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;3', '50', '4']\
Final data (numbers in list format): [1, 2, 3, 50, 4]
                
                
================================================================
                
  
**Sample Input 2:**
'[1,&nbsp; &nbsp;&nbsp; &nbsp;2&nbsp; &nbsp;,&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;3, 50, 4]'

**Sample Output 2:**\
Original data: [1,&nbsp; &nbsp;&nbsp; &nbsp;2&nbsp; &nbsp;,&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;3, 50, 4]\
After removing square brackets: 1,&nbsp; &nbsp;&nbsp; &nbsp;2&nbsp; &nbsp;,&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;3, 50, 4\
Numbers in string format with extra white spaces: ['1', '&nbsp; &nbsp;&nbsp; &nbsp;2&nbsp; &nbsp;', '&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;3', '50', '4']\
Final data (numbers in list format): [1, 2, 3, 50, 4]
                
                
================================================================

                
  
**Sample Input 3:**\
"&nbsp; &nbsp;&nbsp; &nbsp;[1,&nbsp; &nbsp;2&nbsp; &nbsp;,&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;3,&nbsp; &nbsp;50,&nbsp; &nbsp;4]&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;"

**Sample Output 3:**\
Original data: &nbsp; &nbsp;&nbsp; &nbsp;1,&nbsp; &nbsp;2&nbsp; &nbsp;,&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;3,&nbsp; &nbsp;50,&nbsp; &nbsp;4&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;\
After removing square brackets: 1,&nbsp; &nbsp;2&nbsp; &nbsp;,&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;3,&nbsp; &nbsp;50,&nbsp; &nbsp;4\
Numbers in string format with extra white spaces: [' 1', '&nbsp; &nbsp;2&nbsp; &nbsp;', '&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;3', '&nbsp; &nbsp;50', '&nbsp; &nbsp;4']\
Final data (numbers in list format): [1, 2, 3, 50, 4]

                
================================================================
"""

#to do

"""
### Task 17
Write a Python program that takes a single string as an input from the user where few numbers are separated by commas. Now, make a list with the numbers of the given string.Then your task is to remove multiple occurences of any number and then finally print the list **without any duplicate values**.

*Hint (1): For obtaining the numbers from the string, use split(). For cleaning the data, use strip().*

*Hint (2): You may create a third list to store the results. You can use membership operators (in, not in) to make sure no duplicates are added.*

===================================================================

**Sample Input 1:**<br/>
0, 0, 1, 2, 3, 4,&nbsp;&nbsp; &nbsp;&nbsp; 4, 5, 6, 6, 6,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;7, 8, 9, 4,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4<br/>


**Sample Output 1:**<br/>
Given numbers in list: [0, 0, 1, 2, 3, 4, 4, 5, 6, 6, 6, 7, 8, 9, 4, 4]\
List without any dupliacte values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]<br/>

===================================================================

**Sample Input 2:**<br/>
7, 7, 7, 1, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0, 3, 3, &nbsp;&nbsp;55, 9<br/>


**Sample Output 2:**<br/>
Given numbers in list: [7, 7, 7, 1, 0, 3, 3, 55, 9]\
List without any dupliacte values: [7, 1, 0, 3, 55, 9]<br/>

===================================================================
"""

#to do