# -*- coding: utf-8 -*-
"""CSE110 Lab Assignment 3 (String).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z35gqpHeM3-L-uMxbLPlZUJLpZUDMYIq

# CSE110 Lab Assignment 3

This Assignment is to help you develop your concept of Strings in Python.

##Write your name, student ID and CSE110 theory section number below:
"""

#STUDENT NAME:
#STUDENT ID:
#CSE110 THEORY SECTION:

"""## Write the code in Python to do the following tasks:

**<font color='red'>[MUST MAINTAIN VARIABLE NAMING CONVENTIONS FOR ALL THE TASKS]</font>**


### Task 1 

Write a Python program that will ask the user to input a string (containing exactly one word). Then your program should print subsequent substrings of the given string as shown in the examples below.

=====================================================================

**Example 1:**\
Input:\
BANGLA

Output:\
B\
BA\
BAN\
BANG\
BANGL\
BANGLA

=====================================================================

**Example 2:**\
Input:\
DREAM

Output:\
D\
DR\
DRE\
DREA\
DREAM

=====================================================================

**Hints(1):** You may use "for loop" for this task.

**Hints(2):** You may use print() function for printing newlines.

For example:\
print(1)\
print(2)

Output:\
1\
2

=====================================================================

We can use print(end = "") to skip printing the additional newline.

For example:\
print(1, end ="")\
print(2)

Output:(prints the following output right next to the previous one)\
12

=====================================================================





"""

s=input("Enter a String :")
m=len(s)
for row in range(m):
  for col in range(row+1):
    print(s[col], end="")
  print()

num1 = 99
var1 = "CSE110"
      # 012345
      #    -2-1
#var2 = "is very easy"
#print(var1+" "+var2)#------->string concate
#string character access
print(var1[5])
print(var1[-1])
var2 = var1[2]+var1[3]
print(var2)

"""### Task 2

Write a Python program that will ask the user to enter a  word as an input. 

* If the length of the input string is less than 4, then your program should print the same string as an output. 
* If the input string’s length is greater than 3, then your program should add "er" at the end of the input string. 
* If the input string already ends with "er", then add "est" instead. 
* If the input string already ends with "est", then your program should print the same input string as an output.

=====================================================================

**Example 1:**\
Input: strong\
Output: stronger

=====================================================================

**Example 2:**\
Input: stronger\
Output: strongest

=====================================================================

**Example 3:**\
Input: strongest\
Output: strongest

=====================================================================

**Example 4:**\
Input: abc\
Output: abc

=====================================================================
"""

#to do
s=input("Enter a String :")

m=len(s)
if(m<4):
  print(s)
elif m>3 and not(s.endswith('er')) and not(s.endswith('est')):
  print(s+"er")
elif (s.endswith('er')):
  print(s.replace('er','est'))
elif s.endswith("est"):
  print(s)

s=input("Enter a String :")

m=len(s)
if(m<4):
  print(s)
elif m>3 :
  if not(s.endswith('er')) and not(s.endswith('est')):
    print(s+"er")
  elif (s.endswith('er')):
    print(s.replace('er','est'))
  elif s.endswith("est"):
    print(s)

"""### Task 3

Write a Python program that will ask the user to input a string (containing exactly one word). Then print the ASCII code for each character in the String using the ord() function. 

To check if your program is working correctly or not, you can find a list of all correct values from the following website. You may look at “Dec” and “Char” columns only and ignore the other columns for this problem.\
link: http://www.asciitable.com/

=====================================================================

**Example 1:**\
Input: Programming\
Output:\
P : 80\
r : 114\
o : 111\
g : 103\
r : 114\
a : 97\
m : 109\
m : 109\
i : 105\
n : 110\
g : 103

=====================================================================

**Example 2:**\
Input: hunger\
Output:\
h : 104\
u : 117\
n : 110\
g : 103\
e : 101\
r : 114 

=====================================================================
"""

#to do
s='r'
print(ord(s))

"""### Task 4

Take a string as a input from the user with all small letters. Then print the next alphabet in sequence for each alphabet found in the input.

=====================================================================


*Hint: You may need to use the functions ord() and chr(). The ASCII value of ‘a’ is 97 and ‘z’ is 122.*

=====================================================================

**Example 1:**\
Input: abcd\
Output: bcde

=====================================================================

**Example 2:**\
Input: the cow\
Output: uif!dpx

=====================================================================

**Example 3: <font color='red'>[Must fulfil this criteria]</font>**\
Input: xyzabc\
Output: yzabcd

=====================================================================

"""

#to do
s='abcd'
m=len(s)
for i in range(m):
  x=ord(s[i])
  print(chr(x+1),end="")

"""### Task 5

Write a Python program that will ask the user to enter two strings (s1, s2) as an input. Then create a mixed string with alternative characters from each string. Any leftover chars will be appended at the end of the resulting string.

=====================================================================

*Hint: For adding the leftover characters you may use string slicing.*

=====================================================================

**Example 1:**\
Input:\
ABCD\
efgh

Output:\
AeBfCgDh

=====================================================================

**Example 2:**\
Input:\
ABCDENDFGH\
ijkl

Output:\
AiBjCkDlENDFGH

=====================================================================

**Example 3:**\
Input:\
ijkl\
ABCDENDFGH

Output:\
iAjBkClDENDFGH

=====================================================================

"""

#todo
s="abcdefghi"
x="EFGHIJ"
max=-100
if(len(s)>len(x)):
  max=len(s)
else:
  max=len(x)
for i in range(max):
  if(i>=len(s)):
    pass
  else:
    print(s[i],end="")
  if(i>=len(x)):
    pass
  else:
    print(x[i], end="")

"""### Task 6
Given a string, create a new string with all the **consecutive duplicates removed**. 

=====================================================================

**Hint:** You may make a new string to store the result. You can check whether the current character and the next character are the same, then add that character to the new string.

=====================================================================


**Sample Input**:\
AAABBBBCDDBBECE

**Sample Output:**\
ABCDBECE

=====================================================================

"""

#to do
s="AAABBBBCDDBBECE"
m=len(s)
#print(m)
t=""
i=0
for i in range(1,m):
  if(s[i-1]!=s[i]):
    t+=s[i-1]
if(i==m-1 and s[i-1]!=s[i]):
  t+=s[i]
print(t)

"""### Task 7

Write a python program that takes 2 inputs from the user, where the first input is a string with length greater than 1. The second input is the index of the first given string from where you have to start reversing. Then print the new string back to the user.

=====================================================================

**Sample Input 1:**

72418

4

**Sample Output 1:**

81427


**Explanation**: Our second input, index '4' is the last index of our first input String '72418', hence the entire string is reversed giving us '81427'.

=====================================================================

**Sample Input 2:**

12345 

2

**Sample Output 2:**

32145

**Explanation**: The second input is '2' so we have to reverse from index 2 of our first input. The 2nd index of our first input String is '3', index 1 is '2' and index 0 is '1'. Hence, if we reverse indexes 0 to 2, we get '321'. Index 3 and 4 which is '4' and '5' respectively remains unchanged hence our final output is '32145'.

=====================================================================

**Sample Input 3:**

aBcd1234defg

5

**Sample Output 3:**

21dcBa34defg

**Explanation**: From our first input String 'aBcd1234defg', 

index 0 = 'a'

index 1 = 'B'

index 2 = 'c'

index 3 = 'd'

index 4 = '1'

index 5 = '2'

index 6 = '3'

Since our second input is 5, index 0 to index 5 is reversed and we have '21dcBa' and the rest is unchanged from indexes 6 to 11 ('34defg'). Therefore, we have '21dcBa34defg' finally.

=====================================================================

"""

#to do
s="123456"
m=3
n=m
while(n>=0):
  print(s[n], end="")
  n-=1
m+=1
for i in range(m,len(s)):
  print(s[i], end="")

"""### Task 8

Write a python program that splits a given string on a given split character. The first input is a String and the second input is the character that will be used to split the first String. <font color='red'>[You cannot use the built-in split function]</font>

=====================================================================

**Sample Input 1:**<br/>
This-is-CSE110<br/>
-<br/>

**Sample Output 1:**<br/>
This<br/>
is<br/>
CSE110

**Explanation**: The second input which is the character '-', is used to split or divide the first input String 'This-is-CSE110' into 'This', 'is' and 'CSE110' which are printed individually in seperate lines.

=====================================================================

**Sample Input 2**:
tom@gmail,harry@yahoo,bob@gmail,mary@gmail

,

**Sample Output 2**:

tom@gmail

harry@yahoo

bob@gmail

mary@gmail

=====================================================================
"""

#to do
s="tom@gmail,harry@yahoo,bob@gmail,mary@gmail"
c=","
m=0
for i in range(len(s)):
  if(s[i]!=","):
    print(s[i],end="")
  else:
    print()

"""### Task 9

Suppose you are given two strings, s1, and s2. Now, print a new string made up of the last characters and then the first characters of the input strings.

=====================================================================

**Sample Input 1**:

s1 = new

s2= string

**Sample Output 1**:

gwsn

**Explanation:** The last character of the String s2 is 'g'. The last character of the String s1 is 'w'. The first character of the String s2 is 's'. The first character of the String s1 is 'n'. Together they give us the ouput we want 'gwsn'.

=====================================================================

**Sample Input 2**:

s1 = abcd

s2= efgh

**Sample Output 2**: 

hdea

**Explanation:** The last characters of the Strings s2 and s1 is 'h' and 'd' respectively while the first characters of the Strings is 'e' and 'a' respectively. Together they give us the ouput we want 'gwsn'.

=====================================================================

"""

#to do
s1="new"
s2="string"
s3=''
s3+=s2[len(s2)-1]
s3+=s1[len(s1)-1]
s3+=s2[0]
s3+=s1[0]
print(s3)

"""### Task 10

Write a Python program that takes a String as input from the user, removes the characters at even index and prints the resulting String in uppercase.

=====================================================================

**Sample Input 1**:

String

**Sample Output 1**: 

TIG

**Explanation**: The characters 'S', 'r' and 'n' are at index positions 0, 2, and 4 respectively. Hence they are removed and the remaining characters 'tig' are capitalized giving us output 'TIG'.

=====================================================================

**Sample Input 2**:

abcd

**Sample Output 2**: 

BD

=====================================================================

"""

#to do
s="String"
x=''
for i in range(len(s)):
  if(i%2!=0):
    x+=s[i]
print(x.upper())

"""### Task 11

Write a python program that takes two inputs. The first input is a string and the second input is a number. If the number is even then concatenate the given string two times the given number and if the number is odd then concatenate the given string three times the given number.

=====================================================================

**Sample Input 1**:

CSE110

4

**Sample output 1**:

CSE110CSE110CSE110CSE110CSE110CSE110CSE110CSE110

**Explanation**: The second input which is the number 4 is even, therefore the first string input 'CSE110' is concatenated(joined together) 4*2 = 8 times.

=====================================================================

**Sample Input 2**:

CSE110

3

**Sample Output 2**:

CSE110CSE110CSE110CSE110CSE110CSE110CSE110CSE110CSE110

=====================================================================

"""

#to do
s="CSE110"
n=3
if(n%2==0):
  n=n*2
else:
  n=n*3
for i in range(n):
  print(s, end='')

"""### Task 12

Write a python program that takes 2 inputs from the user. The first input is a string and the second input is a letter. The program should remove all occurences of the letter from the given string and print the output. If the letter is not found in the string and the length of string is greater than 3, then remove the first letter and last letter of the given string and print it. Otherwise print the string as it is. [You can assume that all the input will be in lowercase letter]

=====================================================================


**Sample Input 1**:

tanjiro kamado

a

**Sample output 1**:

tnjiro kmdo

**Explanation**: All 3 instances of the character 'a' is removed from the input String 'tanjiro kamado' to give us output 'tnjiro kmdo'.

=====================================================================

**Sample Input 2**:

eren yeager

k


**Sample Output 2**:

ren yeage

**Explanation**: The character 'k' is absent in the first input String 'eren yeager' and it's length is 11 which is greater than 3 therefore the first character 'e' and the last character 'r' is removed. Hence, the final String is 'ren yeage'.

=====================================================================

Sample Input 3:

hi

a

Sample Output 3:

hi

**Explanation**: The letter 'a' is not found in our first input 'hi', the length of which is 2. Since the character is not present and the length is less than 3, we print the String 'hi' as it is.

=====================================================================

"""

#to do
s="hi"
k="k"
c=0
for i in range(len(s)):
  if(s[i]==k):
    c+=1

if (c!=0):
  for i in range(len(s)):
    if(s[i]!=k):
      print(s[i],end='')
elif len(s)>3:
  for i in range(1,len(s)-1):
    print(s[i],end='')
else:
  print(s)

"""## Optional Tasks (13 - 15) [Ungraded]

### Task 13


Write a python program that takes a string as an input from the user and then modifies the string in such a way that the string always starts with an uppercase letter and the case of each subsequent letter is the opposite of the previous letter (uppercase character followed by a lowercase character followed by an uppercase character and so on).  Finally the modified string is printed to show the user.

*Hint:  Flags/counters can be used to manage uppercase-lowercase.*

=====================================================================

**Sample Input 1:**\
Python programming is very easy

**Sample Output 1:**\
PyThOn PrOgRaMmInG iS vErY eAsY

=====================================================================

**Sample Input 2:**\
I&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;     love       &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Python &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Programming

**Sample Output 2:**\
I&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;     lOvE       &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pYtHoN&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pRoGrAmMiNg

=====================================================================

**Sample Input 3:**\
CSE110 Course

**Sample Output 3**\
CsE110 cOuRsE



=====================================================================

**Sample Input 4:**\
c

**Sample Output 4:**\
C

=====================================================================
"""

#to do

"""### Task 14 
An anagram is a play on words created by rearranging the letters of the original word to make a new word or phrase.
So we can say two words are anagrams if they contain all of the same letters, but in a different order.


Write a python program that takes two strings from the user and tells if they are anagram or not.

=====================================================================

<b>Sample Input 1: </b><br/>
dusty<br/>
study<br/>
<b>Sample Output 1: </b> <br/>
They are anagram<br/>

=====================================================================

<b>Sample Input 2: </b><br/>
dustyyy<br/>
study<br/>
<b>Sample Output 2: </b><br/>
They are not anagram
"""

# to do
s1="dusty"
s2="study"
f=True
if len(s1)==len(s2):
  for i in range(len(s1)):
    if s2[i] in s1:
      pass
    else:
      f=False
  if f :
    print('They are anagram')
  else:
    print('They are not anagram')
else:
  print('They are not anagram')

"""###Task 15

Write a python program thats prints the largest consecutive sequence from a given string S. For example, if S = ‘AABBBCCAAAA’, print ‘AAAA’. If more than one largest consecutive sequence exists, print the first one. Print NONE if no consecutive sequence is found.

=====================================================================

**Sample Input 1:**<br/>
AABBBCCAAAA<br/>
**Sample Output 1:**<br/>
AAAA<br/>

=====================================================================

**Sample Input 2:**<br/>
AABBCC<br/>
**Sample Output 2:**<br/>
AA<br/>

=====================================================================

**Sample Input 3:**<br/>
ABCD<br/>
**Sample Output 3:**<br/>
NONE<br/>

=====================================================================
"""

#to do